services:
  user-manager-service:
    depends_on:
      - isla-del-lago-database
    build: .
    ports:
      - 9000:9000
    expose:
      - 9000
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_SCHEMA: ${DATABASE_SCHEMA}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SIGNATURE_SECRET: ${JWT_SIGNATURE_SECRET}

  isla-del-lago-database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${DATABASE_SCHEMA}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    expose:
      - 3306
